version: '3'

services:
  database:
    container_name: mysql_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: icedb
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d # MySQL 설정 파일 위치
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  redis:
    image: redis
    container_name: token-redis
    command: redis-server --port 6379
    restart: always
    hostname: redis
    ports:
      - "6379:6379"