server:
  port: 8081

#spring:
#  profiles:
#    active: local

spring:
  config:
    activate:
      on-profile: local

spring:jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
  hibernate.ddl-auto: create
  show-sql: true
properties:
  hibernate.format_sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://localhost:5432/ice_users
  username: postgres
  password: test12
  driver-class-name: org.postgresql.Driver


eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Ice-Americano Page

secretKey: amazing